# This is a basic workflow to help you get started with Actions

name: Example CI Django

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: lms_admin
          POSTGRES_PASSWORD: lms
          POSTGRES_DB: lms_new
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: "0"
          DJANGO_SECRET_KEY: CI_CD_TEST_KEY
          POSTGRES_USER: lms_admin
          POSTGRES_PASSWORD: lms
          POSTGRES_DB: lms_new
          POSTGRES_PORT: 5432
        run: |              
              cd /home/legal/lms-backend
              
              git pull origin legalprosystem-staging
              
              cd /home/legal/
              
              source lmsenv/bin/activate
              
              cd lms-backend
              
              pip3 install -r requirements.txt
              
              deactivate
              
              python3 manage.py run_migration
              
              systemctl daemon-reload
              
              systemctl restart daphne.service
