name: Django CI/CD Pipeline

on:
  push:
    branches:
      - legalprosystem-staging  # or staging, or any other branch you want to deploy from

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py run_migration
          systemctl daemon-reload
          systemctl restart daphne.service
